version: '3.9'

networks:
  web_network:
    name: laravel8
    driver: bridge

services:

  # PHP Service
  app:
    build:
      context: .
    image: laravel8-app
    container_name: laravel8-app
    restart: always
    volumes:
      - ./src/laravel:/var/www
    networks:
      - web_network

  # MySql Database Service
  db:
    image: mariadb
    container_name: laravel8-db
    volumes:
      - ./mariadb/data/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=laravelDb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
    ports:
      - "3307:3306"
    restart: always
    networks:
      - web_network

  # Nginx Web Server Service
  nginx: 
    image: nginx:1.19.8-alpine
    container_name: laravel8-nginx
    volumes:
      - ./src/laravel:/var/www
      - ./nginx/conf:/etc/nginx/conf.d
    ports:
      - "8100:80"
    networks:
      - web_network

  redis:
    image: redis:6.2.1-buster
    container_name: laravel-redis
    volumes:
      - ./redis/data:/data
    restart:  always
    networks:
      - web_network
  
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: laravel8_mailhog
    ports:
      - 8025:8025
    restart: always
    tty: true
    networks:
      - web_network
  
  phpmyadmin:
    image: phpmyadmin:5.1.0-apache
    depends_on:
      - db
    container_name: laravel8-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: 1234
    ports:
      - 8200:80
    restart: always
    tty: true
    networks:
      - web_network